name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy code to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: ./
        target: /home/ubuntu

    # - name: Start Docker Compose
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.EC2_KEY }}
    #     port: 22
    #     script: |
    #       cd /home/ubuntu
    #       sudo docker compose down
    #       sudo docker compose up --build -d
